{
  inputs,
  lib,
  pkgs,
}:
let
  llmAgents = inputs.llm-agents.packages.${pkgs.stdenv.hostPlatform.system};

  yamlFormat = pkgs.formats.yaml { };

  inherit (lib)
    concatMapStringsSep
    escapeShellArg
    filterAttrs
    mapAttrsToList
    nameValuePair
    recursiveUpdate
    ;

  mkOmpConfig =
    {
      theme ? { },
      symbolPreset ? "unicode",
      defaultThinkingLevel ? "high",
      hideThinkingBlock ? false,
      terminal ? { },
      display ? { },
      steeringMode ? "one-at-a-time",
      followUpMode ? "one-at-a-time",
      interruptMode ? "immediate",
      compaction ? { },
      skills ? { },
      memories ? { },
      temperature ? -1,
      topP ? -1,
      topK ? -1,
      minP ? -1,
      modelRoles ? { },
      enabledModels ? [ ],
      modelProviderOrder ? [ ],
      disabledProviders ? [ ],
      retry ? { },
      edit ? { },
      read ? { },
      lsp ? { },
      bashInterceptor ? { },
      shellMinimizer ? { },
      branchSummary ? { },
      contextPromotion ? { },
      autoResume ? false,
      marketplace ? { },
      statusLine ? { },
      extensions ? [ ],
      disabledExtensions ? [ ],
      extraConfig ? { },
    }:
    let
      defaultTheme = {
        dark = "titanium";
        light = "light";
      };
      defaultTerminal = {
        showImages = true;
      };
      defaultDisplay = {
        tabWidth = 3;
      };
      defaultCompaction = {
        enabled = true;
        reserveTokens = 16384;
        keepRecentTokens = 20000;
        autoContinue = true;
        strategy = "context-full";
        remoteEnabled = true;
        thresholdPercent = -1;
        thresholdTokens = -1;
      };
      defaultSkills = {
        enabled = true;
      };
      defaultMemories = {
        enabled = false;
      };
      defaultRetry = {
        enabled = true;
        maxRetries = 3;
      };
      defaultModelRoles = {
        default = "claude-sonnet-4-6";
        smol = "claude-haiku-4-5";
      };
      defaultEnabledModels = [
        "anthropic/*"
        "openai/*"
      ];
      defaultModelProviderOrder = [
        "anthropic"
        "openai"
      ];
      defaultEdit = {
        mode = "hashline";
        fuzzyMatch = true;
        blockAutoGenerated = true;
      };
      defaultRead = {
        lineNumbers = false;
        hashLines = true;
        defaultLimit = 500;
      };
      defaultLsp = {
        enabled = true;
        formatOnWrite = false;
        diagnosticsOnWrite = true;
      };
      defaultBashInterceptor = {
        enabled = false;
      };
      defaultShellMinimizer = {
        enabled = true;
      };
      defaultBranchSummary = {
        enabled = false;
      };
      defaultContextPromotion = {
        enabled = true;
      };
      defaultMarketplace = {
        autoUpdate = "notify";
      };
    in
    recursiveUpdate {
      theme = recursiveUpdate defaultTheme theme;
      inherit symbolPreset defaultThinkingLevel hideThinkingBlock;
      terminal = recursiveUpdate defaultTerminal terminal;
      display = recursiveUpdate defaultDisplay display;
      inherit steeringMode followUpMode interruptMode;
      compaction = recursiveUpdate defaultCompaction compaction;
      skills = recursiveUpdate defaultSkills skills;
      memories = recursiveUpdate defaultMemories memories;
      inherit
        temperature
        topP
        topK
        minP
        ;
      retry = recursiveUpdate defaultRetry retry;
      modelRoles = recursiveUpdate defaultModelRoles modelRoles;
      enabledModels = if enabledModels != [ ] then enabledModels else defaultEnabledModels;
      modelProviderOrder =
        if modelProviderOrder != [ ] then modelProviderOrder else defaultModelProviderOrder;
      inherit disabledProviders;
      edit = recursiveUpdate defaultEdit edit;
      read = recursiveUpdate defaultRead read;
      lsp = recursiveUpdate defaultLsp lsp;
      bashInterceptor = recursiveUpdate defaultBashInterceptor bashInterceptor;
      shellMinimizer = recursiveUpdate defaultShellMinimizer shellMinimizer;
      branchSummary = recursiveUpdate defaultBranchSummary branchSummary;
      contextPromotion = recursiveUpdate defaultContextPromotion contextPromotion;
      inherit autoResume;
      marketplace = recursiveUpdate defaultMarketplace marketplace;
      statusLine = statusLine;
      inherit extensions disabledExtensions;
    } extraConfig;

  mkOmpModels =
    {
      providers ? { },
      equivalence ? { },
    }:
    filterAttrs (_: v: v != { } && v != [ ]) {
      providers = if providers != { } then providers else { };
      equivalence = if equivalence != { } then equivalence else { };
    };

  mkOmpWrapper =
    profile: runMode:
    let
      commandName = if runMode then profile.runCommandName else profile.commandName;
      configDir = if profile.configDir != null then profile.configDir else ".omp";
      envVars = profile.env or { };
      envFileVars = profile.envFiles or { };
      package = if profile ? package && profile.package != null then profile.package else llmAgents.omp;
    in
    pkgs.writeShellApplication {
      name = commandName;
      runtimeInputs = [ package ] ++ (profile.extraRuntimePackages or [ ]);
      text = ''
        export PI_CONFIG_DIR=${escapeShellArg configDir}
      ''
      + lib.concatMapStrings (k: ''
        # shellcheck disable=SC2016
        export ${k}=${escapeShellArg envVars.${k}}
      '') (builtins.attrNames envVars)
      + lib.concatMapStrings (k: ''
        ${k}="$(< ${escapeShellArg envFileVars.${k}})"
        export ${k}
      '') (builtins.attrNames envFileVars)
      + ''

        exec ${lib.getExe package} "$@"
      '';
    };

  defaultPermissionGateBlockedPatterns = [
    {
      pattern = "\\brm\\s+(-[^\\s]*r[^\\s]*\\s|-[^\\s]*rf\\s)";
      flags = "i";
    }
    {
      pattern = "\\bsudo\\b";
      flags = "i";
    }
    {
      pattern = "\\bchmod\\s+(-R\\s+)?777\\b";
      flags = "i";
    }
    {
      pattern = "\\bchown\\s+(-R\\s+)?root\\b";
      flags = "i";
    }
    {
      pattern = "\\bmkfs\\b";
      flags = "i";
    }
    {
      pattern = "\\bdd\\s+if=";
      flags = "i";
    }
    {
      pattern = "\\b:(){ :|:& };:";
      flags = "";
    }
    {
      pattern = "\\bwget\\s+.*\\|\\s*(ba)?sh\\b";
      flags = "i";
    }
    {
      pattern = "\\bcurl\\s+.*\\|\\s*(ba)?sh\\b";
      flags = "i";
    }
    {
      pattern = "\\bgit\\s+push\\b";
      flags = "";
    }
  ];

  defaultPermissionGateBlockedCommands = [
    "reboot"
    "shutdown"
    "poweroff"
    "halt"
  ];

  defaultProtectedPathGlobs = [
    ".env"
    ".env.*"
    ".git/**"
    "node_modules/**"
    ".direnv/**"
    ".devenv/**"
    ".omp/**"
  ];

  mkRegExpEntries =
    patterns:
    concatMapStringsSep "\n" (
      pattern:
      "      new RegExp(${builtins.toJSON pattern.pattern}, ${builtins.toJSON (pattern.flags or "")}),"
    ) patterns;

  mkPermissionGateHook =
    {
      blockedPatterns ? defaultPermissionGateBlockedPatterns,
      blockedCommands ? defaultPermissionGateBlockedCommands,
      extraBlockedPatterns ? [ ],
      extraBlockedCommands ? [ ],
      mode ? "ask",
      ...
    }:
    let
      allBlockedPatterns = blockedPatterns ++ extraBlockedPatterns;
      allBlockedCommands = blockedCommands ++ extraBlockedCommands;
      modeAsk = mode == "ask";
    in
    ''
      ${lib.optionalString modeAsk (mkGrantsHelper {
        grantNamespace = "permissionGate";
      })}

      var BLOCKED_PATTERNS = [
      ${mkRegExpEntries allBlockedPatterns}
      ]

      var BLOCKED_COMMANDS = ${builtins.toJSON allBlockedCommands}

      export default function (pi) {
        pi.on("tool_call", ${if modeAsk then "async function" else "function"} (call, ctx) {
          if (call.toolName !== "bash" && call.toolName !== "shell") return

          var command = String(call.input?.command ?? "")
          if (!command) return

          for (var i = 0; i < BLOCKED_PATTERNS.length; i++) {
            if (BLOCKED_PATTERNS[i].test(command)) {
      ${
        if modeAsk then
          ''
            var grant = checkGrant(command)
            if (grant) return
            if (!ctx.hasUI) return { block: true, reason: "Permission gate blocked: command matches dangerous pattern" }
            var choice = await ctx.ui.select("Permission Gate", "Command: " + command + " may be dangerous.", [
              { label: "Allow once", value: "once" },
              { label: "Allow for session", value: "session" },
              { label: "Always allow", value: "always" },
              { label: "Deny", value: "deny" }
            ])
            if (!choice || choice === "deny") return { block: true, reason: "Permission gate: user denied command" }
            if (choice === "once") return
            saveGrant(command, choice)
          ''
        else
          ''
            return { block: true, reason: "Permission gate blocked: command matches dangerous pattern" }
          ''
      }
            }
          }

          var firstWord = command.trim().split(/\s+/)[0] ?? ""
          if (BLOCKED_COMMANDS.includes(firstWord)) {
      ${
        if modeAsk then
          ''
            var cmdGrant = checkGrant(firstWord)
            if (cmdGrant) return
            if (!ctx.hasUI) return { block: true, reason: "Permission gate blocked: " + firstWord + " is not allowed" }
            var cmdChoice = await ctx.ui.select("Permission Gate", firstWord + " is not allowed.\nCommand: " + command, [
              { label: "Allow once", value: "once" },
              { label: "Allow for session", value: "session" },
              { label: "Always allow", value: "always" },
              { label: "Deny", value: "deny" }
            ])
            if (!cmdChoice || cmdChoice === "deny") return { block: true, reason: "Permission gate: user denied command" }
            if (cmdChoice === "once") return
            saveGrant(firstWord, cmdChoice)
          ''
        else
          ''
            return { block: true, reason: "Permission gate blocked: " + firstWord + " is not allowed" }
          ''
      }
          }
        })
      }
    '';

  mkProtectedPathsHook =
    {
      globs ? defaultProtectedPathGlobs,
      extraGlobs ? [ ],
      protectReads ? true,
      ...
    }:
    let
      allGlobs = globs ++ extraGlobs;
      readToolGuard =
        if protectReads then
          ''
            if (call.toolName !== "write" && call.toolName !== "edit" && call.toolName !== "filesystem_write_file" && call.toolName !== "read" && call.toolName !== "find" && call.toolName !== "search" && call.toolName !== "grep" && call.toolName !== "filesystem_read_file" && call.toolName !== "filesystem_list_directory") return
          ''
        else
          ''
            if (call.toolName !== "write" && call.toolName !== "edit" && call.toolName !== "filesystem_write_file") return
          '';
      reasonPrefix = if protectReads then "Protected path: accessing " else "Protected path: writing to ";
    in
    ''
      const PROTECTED_GLOBS = ${builtins.toJSON allGlobs}

      function matchesProtected(fp: string): boolean {
        for (const glob of PROTECTED_GLOBS) {
          if (glob.endsWith("/**")) {
            const prefix = glob.slice(0, -3)
            if (fp === prefix || fp.startsWith(prefix + "/")) return true
          } else {
            if (fp === glob) return true
          }
        }
        return false
      }

      export default (pi) => {
        pi.on("tool_call", (call, ctx) => {
          ${readToolGuard}

          const fp = String(call.input?.filePath ?? call.input?.path ?? call.input?.directory ?? call.input?.pattern ?? "")
          if (matchesProtected(fp)) {
            return { block: true, reason: "${reasonPrefix}" + fp + " is blocked" }
          }
        })
      }
    '';

  mkGrantsHelper =
    { grantNamespace }:
    let
      grantsFile = "agent/extensions/grants.json";
    in
    ''
      var sessionGrants: Record<string, string> = {}
      var alwaysGrants: Record<string, string> = {}

      function loadGrants(): void {
        try {
          var fs = require("fs")
          var path = require("path")
          var configDir = process.env.PI_CONFIG_DIR || ".omp"
          var grantsPath = path.join(configDir, "${grantsFile}")
          if (fs.existsSync(grantsPath)) {
            var data = JSON.parse(fs.readFileSync(grantsPath, "utf8"))
            if (data && typeof data === "object") {
              alwaysGrants = data["${grantNamespace}"] || {}
            }
          }
        } catch (_) {
          // grants file missing or invalid — start empty
        }
      }

      function saveGrant(key: string, scope: string): void {
        if (scope === "always") {
          alwaysGrants[key] = "always"
          try {
            var fs = require("fs")
            var path = require("path")
            var configDir = process.env.PI_CONFIG_DIR || ".omp"
            var grantsPath = path.join(configDir, "${grantsFile}")
            var existing: Record<string, any> = {}
            if (fs.existsSync(grantsPath)) {
              existing = JSON.parse(fs.readFileSync(grantsPath, "utf8"))
            }
            existing["${grantNamespace}"] = alwaysGrants
            fs.mkdirSync(path.dirname(grantsPath), { recursive: true })
            fs.writeFileSync(grantsPath, JSON.stringify(existing, null, 2) + "\n")
          } catch (_) {
            // best effort — don't break the hook if save fails
          }
        } else if (scope === "session") {
          sessionGrants[key] = "session"
        }
      }

      function checkGrant(key: string): string | null {
        if (sessionGrants[key]) return sessionGrants[key]
        if (alwaysGrants[key]) return alwaysGrants[key]
        return null
      }

      loadGrants()
    '';

  defaultPathAccessAllowPaths = [
    "/nix/store"
  ];

  defaultPathAccessDenyPaths = [
    "~/.ssh"
    "~/.gnupg"
  ];

  mkPathAccessHook =
    {
      allowPaths ? defaultPathAccessAllowPaths,
      denyPaths ? defaultPathAccessDenyPaths,
      mode ? "ask",
      ...
    }:
    let
      modeAsk = mode == "ask";
      modeBlock = mode == "block";
    in
    ''
      ${mkGrantsHelper { grantNamespace = "pathAccess"; }}

      var path = require("path")

      const ALLOW_PATHS: string[] = ${builtins.toJSON allowPaths}
      const DENY_PATHS: string[] = ${builtins.toJSON denyPaths}

      function expandHome(fp: string): string {
        if (fp === "~") return process.env.HOME || fp
        if (fp.startsWith("~/")) return (process.env.HOME || "") + fp.slice(1)
        return fp
      }

      function normalizePath(fp: string): string {
        var expanded = expandHome(fp)
        if (!expanded.startsWith("/")) return path.resolve(process.cwd(), fp)
        return path.resolve(expanded)
      }

      function isInsideWorkspace(fp: string): boolean {
        if (!fp) return true
        var cwd = path.resolve(process.cwd())
        return fp === cwd || fp.startsWith(cwd + "/")
      }

      function isPathAllowed(fp: string): boolean {
        for (var i = 0; i < ALLOW_PATHS.length; i++) {
          var allowPath = normalizePath(ALLOW_PATHS[i])
          if (fp === allowPath || fp.startsWith(allowPath + "/")) return true
        }
        return false
      }

      function isPathDenied(fp: string): boolean {
        for (var i = 0; i < DENY_PATHS.length; i++) {
          var d = normalizePath(DENY_PATHS[i])
          if (fp === d || fp.startsWith(d + "/")) return true
        }
        return false
      }

      const PATH_TOOLS = new Set(["read", "write", "edit", "find", "search", "filesystem_read_file", "filesystem_write_file", "filesystem_list_directory"])

      export default function (pi) {
        pi.on("tool_call", ${if modeAsk then "async function" else "function"} (call, ctx) {
          if (!PATH_TOOLS.has(call.toolName)) return

          var fp = String(call.input?.filePath ?? call.input?.path ?? call.input?.directory ?? call.input?.pattern ?? "")
          if (!fp) return

          fp = normalizePath(fp)

          // Check deny list first — always blocks
          if (isPathDenied(fp)) {
            return { block: true, reason: "Path access denied: " + fp + " is in the deny list" }
          }

          // Check allow list — skip workspace check
          if (isPathAllowed(fp)) return

          // Check if inside workspace
          if (isInsideWorkspace(fp)) return

          // Outside workspace — check grants
          var grant = checkGrant(fp)
          if (grant) return

      ${
        if modeAsk then
          ''
            if (!ctx.hasUI) return { block: true, reason: "Path access blocked: " + fp + " is outside workspace" }
            var choice = await ctx.ui.select("Path Access", fp + " is outside the workspace. Allow access?", [
              { label: "Allow once", value: "once" },
              { label: "Allow for session", value: "session" },
              { label: "Always allow", value: "always" },
              { label: "Deny", value: "deny" }
            ])
            if (!choice || choice === "deny") return { block: true, reason: "Path access: user denied " + fp }
            if (choice === "once") return
            saveGrant(fp, choice)
          ''
        else if modeBlock then
          ''
            return { block: true, reason: "Path access blocked: " + fp + " is outside workspace" }
          ''
        else
          ""
      }
        })
      }
    '';

  hooks = {
    permissionGate = mkPermissionGateHook { };
    protectedPaths = mkProtectedPathsHook { };
    pathAccess = mkPathAccessHook { };
  };

  mkYamlConfig =
    profile:
    let
      config = mkOmpConfig profile;
      models = mkOmpModels profile;
    in
    {
      "agent/config.yml".text = yamlFormat.generate "omp-config" config;
      "agent/models.yml".text = yamlFormat.generate "omp-models" models;
    };

  mkHookFile =
    profileName: hookName: hookContent:
    nameValuePair "${profileName}/agent/extensions/${hookName}.ts" { text = hookContent; };

  mkProfileHookFiles =
    profileName: enabledHooks:
    builtins.listToAttrs (
      mapAttrsToList (hookName: _: mkHookFile profileName hookName hooks.${hookName}) (
        filterAttrs (_: enabled: enabled) enabledHooks
      )
    );

in
{
  inherit
    defaultPermissionGateBlockedCommands
    defaultPermissionGateBlockedPatterns
    defaultProtectedPathGlobs
    defaultPathAccessAllowPaths
    defaultPathAccessDenyPaths
    hooks
    mkGrantsHelper
    mkPathAccessHook
    mkPermissionGateHook
    mkProtectedPathsHook
    mkOmpConfig
    mkOmpModels
    mkOmpWrapper
    mkYamlConfig
    mkProfileHookFiles
    ;

  configSuffix = "agent";
}
