{
  inputs,
  lib,
  pkgs,
}:
let
  llmAgents = inputs.llm-agents.packages.${pkgs.stdenv.hostPlatform.system};

  yamlFormat = pkgs.formats.yaml { };

  inherit (lib)
    concatMapStringsSep
    escapeShellArg
    filterAttrs
    mapAttrsToList
    nameValuePair
    optionalAttrs
    recursiveUpdate
    ;

  mkOmpConfig =
    {
      theme ? { },
      symbolPreset ? "unicode",
      defaultThinkingLevel ? "high",
      hideThinkingBlock ? false,
      terminal ? { },
      display ? { },
      steeringMode ? "one-at-a-time",
      followUpMode ? "one-at-a-time",
      interruptMode ? "immediate",
      compaction ? { },
      skills ? { },
      memories ? { },
      temperature ? -1,
      topP ? -1,
      topK ? -1,
      minP ? -1,
      modelRoles ? { },
      enabledModels ? [ ],
      modelProviderOrder ? [ ],
      disabledProviders ? [ ],
      retry ? { },
      edit ? { },
      read ? { },
      lsp ? { },
      bashInterceptor ? { },
      shellMinimizer ? { },
      branchSummary ? { },
      contextPromotion ? { },
      autoResume ? false,
      marketplace ? { },
      statusLine ? { },
      extensions ? [ ],
      disabledExtensions ? [ ],
      extraConfig ? { },
    }:
    let
      defaultTheme = {
        dark = "titanium";
        light = "light";
      };
      defaultTerminal = {
        showImages = true;
      };
      defaultCompaction = {
        enabled = true;
        reserveTokens = 16384;
        keepRecentTokens = 20000;
        autoContinue = true;
        strategy = "context-full";
        remoteEnabled = true;
        thresholdPercent = -1;
        thresholdTokens = -1;
      };
      defaultSkills = {
        enabled = true;
      };
      defaultMemories = {
        enabled = false;
      };
      defaultRetry = {
        enabled = true;
        maxRetries = 3;
      };
      defaultModelRoles = {
        default = "claude-sonnet-4-6";
        smol = "claude-haiku-4-5";
      };
      defaultEnabledModels = [
        "anthropic/*"
        "openai/*"
      ];
      defaultModelProviderOrder = [
        "anthropic"
        "openai"
      ];
      defaultEdit = {
        mode = "hashline";
        fuzzyMatch = true;
        blockAutoGenerated = true;
      };
      defaultRead = {
        defaultLimit = 500;
      };
      defaultLsp = {
        enabled = true;
        formatOnWrite = false;
        diagnosticsOnWrite = true;
      };
      defaultBashInterceptor = {
        enabled = false;
      };
      defaultShellMinimizer = {
        enabled = true;
      };
      defaultBranchSummary = {
        enabled = false;
      };
      defaultContextPromotion = {
        enabled = true;
      };
      defaultMarketplace = {
        autoUpdate = "notify";
      };
      # omp has no `display.tabWidth` setting — `omp config get display.tabWidth`
      # answers "Unknown setting" (checked on 17.3.3 and 17.3.5), so emitting it
      # only wrote a dead key into every config.yml. The real display.* settings
      # are shimmer / smoothStreaming / hideToolActivity / showTokenUsage /
      # cacheMissMarker / collapseCompacted, so `display` stays a pure
      # passthrough with no defaults and is omitted when a caller sets none.
      displayAttrs = optionalAttrs (display != { }) { inherit display; };
    in
    recursiveUpdate {
      theme = recursiveUpdate defaultTheme theme;
      inherit symbolPreset defaultThinkingLevel hideThinkingBlock;
      terminal = recursiveUpdate defaultTerminal terminal;
      inherit steeringMode followUpMode interruptMode;
      compaction = recursiveUpdate defaultCompaction compaction;
      skills = recursiveUpdate defaultSkills skills;
      memories = recursiveUpdate defaultMemories memories;
      inherit
        temperature
        topP
        topK
        minP
        ;
      retry = recursiveUpdate defaultRetry retry;
      modelRoles = recursiveUpdate defaultModelRoles modelRoles;
      enabledModels = if enabledModels != [ ] then enabledModels else defaultEnabledModels;
      modelProviderOrder =
        if modelProviderOrder != [ ] then modelProviderOrder else defaultModelProviderOrder;
      inherit disabledProviders;
      edit = recursiveUpdate defaultEdit edit;
      read = recursiveUpdate defaultRead read;
      lsp = recursiveUpdate defaultLsp lsp;
      bashInterceptor = recursiveUpdate defaultBashInterceptor bashInterceptor;
      shellMinimizer = recursiveUpdate defaultShellMinimizer shellMinimizer;
      branchSummary = recursiveUpdate defaultBranchSummary branchSummary;
      contextPromotion = recursiveUpdate defaultContextPromotion contextPromotion;
      inherit autoResume;
      marketplace = recursiveUpdate defaultMarketplace marketplace;
      statusLine = statusLine;
      inherit extensions disabledExtensions;
    } (recursiveUpdate displayAttrs extraConfig);

  mkOmpWrapper =
    profile: runMode:
    let
      commandName = if runMode then profile.runCommandName else profile.commandName;
      configDir = if profile.configDir != null then profile.configDir else ".omp";
      envVars = profile.env or { };
      envFileVars = profile.envFiles or { };
      package = if profile ? package && profile.package != null then profile.package else llmAgents.omp;
    in
    pkgs.writeShellApplication {
      name = commandName;
      runtimeInputs = [ package ] ++ (profile.extraRuntimePackages or [ ]);
      text = ''
        export PI_CONFIG_DIR=${escapeShellArg configDir}
      ''
      + lib.concatMapStrings (k: ''
        # shellcheck disable=SC2016
        export ${k}=${escapeShellArg envVars.${k}}
      '') (builtins.attrNames envVars)
      + lib.concatMapStrings (k: ''
        ${k}="$(< ${escapeShellArg envFileVars.${k}})"
        export ${k}
      '') (builtins.attrNames envFileVars)
      + ''

        exec ${lib.getExe package} "$@"
      '';
    };

  defaultPermissionGateBlockedPatterns = [
    {
      pattern = "\\brm\\s+(-[^\\s]*r[^\\s]*\\s|-[^\\s]*rf\\s)";
      flags = "i";
    }
    {
      pattern = "\\bsudo\\b";
      flags = "i";
    }
    {
      pattern = "\\bchmod\\s+(-R\\s+)?777\\b";
      flags = "i";
    }
    {
      pattern = "\\bchown\\s+(-R\\s+)?root\\b";
      flags = "i";
    }
    {
      pattern = "\\bmkfs\\b";
      flags = "i";
    }
    {
      pattern = "\\bdd\\s+if=";
      flags = "i";
    }
    {
      pattern = ":\\(\\)\\s*\\{\\s*:\\s*\\|\\s*:\\s*&\\s*\\}\\s*;\\s*:";
      flags = "";
    }
    {
      pattern = "\\bwget\\s+.*\\|\\s*(ba)?sh\\b";
      flags = "i";
    }
    {
      pattern = "\\bcurl\\s+.*\\|\\s*(ba)?sh\\b";
      flags = "i";
    }
    {
      pattern = "\\bgit\\s+push\\b";
      flags = "";
    }
    {
      pattern = "\\bbrew\\b";
      flags = "i";
    }
    {
      pattern = "\\bterraform\\s+apply\\b";
      flags = "i";
    }
    {
      pattern = "\\bterraform\\s+destroy\\b";
      flags = "i";
    }
    {
      pattern = "\\bkubectl\\s+delete\\b";
      flags = "i";
    }
    {
      pattern = "\\bdocker\\s+system\\s+prune\\b";
      flags = "i";
    }
    {
      pattern = "\\bnpm\\s+publish\\b";
      flags = "i";
    }
    {
      pattern = "\\byarn\\s+publish\\b";
      flags = "i";
    }
    {
      pattern = "\\bpnpm\\s+publish\\b";
      flags = "i";
    }
    {
      pattern = "\\bDROP\\s+DATABASE\\b";
      flags = "i";
    }
    {
      pattern = "\\bDROP\\s+TABLE\\b";
      flags = "i";
    }
    {
      pattern = "\\bdbt\\s+run\\b";
      flags = "i";
    }
    {
      pattern = "\\bdbt\\s+seed\\b";
      flags = "i";
    }
    {
      pattern = "\\baws\\s+s3\\s+rm\\b";
      flags = "i";
    }
    {
      pattern = "\\baws\\s+iam\\b";
      flags = "i";
    }
    {
      pattern = "\\baws\\s+ec2\\s+terminate-instances\\b";
      flags = "i";
    }
    {
      pattern = "\\bkubectl\\s+apply\\b";
      flags = "i";
    }
    {
      pattern = "\\bkubectl\\s+scale\\b";
      flags = "i";
    }
    {
      pattern = "\\bdocker\\s+rm\\b";
      flags = "i";
    }
    {
      pattern = "\\bdocker\\s+rmi\\b";
      flags = "i";
    }
    {
      pattern = "\\bdocker\\s+compose\\s+down\\b";
      flags = "i";
    }
    {
      pattern = "\\bterraform\\s+import\\b";
      flags = "i";
    }
    {
      pattern = "\\bgcloud\\s+compute\\s+instances\\s+delete\\b";
      flags = "i";
    }
    {
      pattern = "\\bgcloud\\s+iam\\b";
      flags = "i";
    }
    {
      pattern = "\\bgcloud\\s+sql\\s+instances\\s+delete\\b";
      flags = "i";
    }
  ];

  defaultPermissionGateBlockedCommands = [
    "reboot"
    "shutdown"
    "poweroff"
    "halt"
  ];

  defaultProtectedPathGlobs = [
    ".env"
    ".env.*"
    ".git/**"
    "node_modules/**"
    ".direnv/**"
    ".devenv/**"
    ".omp/**"
  ];

  mkRegExpEntries =
    patterns:
    concatMapStringsSep "\n" (
      pattern:
      "      new RegExp(${builtins.toJSON pattern.pattern}, ${builtins.toJSON (pattern.flags or "")}),"
    ) patterns;

  mkPermissionGateHook =
    {
      blockedPatterns ? defaultPermissionGateBlockedPatterns,
      blockedCommands ? defaultPermissionGateBlockedCommands,
      extraBlockedPatterns ? [ ],
      extraBlockedCommands ? [ ],
      mode ? "ask",
      ...
    }:
    let
      allBlockedPatterns = blockedPatterns ++ extraBlockedPatterns;
      allBlockedCommands = blockedCommands ++ extraBlockedCommands;
      modeAsk = mode == "ask";
    in
    ''
      ${lib.optionalString modeAsk (mkGrantsHelper {
        grantNamespace = "permissionGate";
      })}

      var BLOCKED_PATTERNS = [
      ${mkRegExpEntries allBlockedPatterns}
      ]

      var BLOCKED_COMMANDS = ${builtins.toJSON allBlockedCommands}

      export default function (pi) {
        pi.on("tool_call", ${if modeAsk then "async function" else "function"} (call, ctx) {
          if (call.toolName !== "bash" && call.toolName !== "shell") return

          var command = String(call.input?.command ?? "")
          if (!command) return

          for (var i = 0; i < BLOCKED_PATTERNS.length; i++) {
            if (BLOCKED_PATTERNS[i].test(command)) {
      ${
        if modeAsk then
          ''
            var grant = checkGrant(command)
            if (grant) return
            if (!ctx.hasUI) return { block: true, reason: "Permission gate blocked: command matches dangerous pattern" }
            if (!ctx.ui || typeof ctx.ui.select !== "function") return { block: true, reason: "Permission gate blocked: command matches dangerous pattern" }
            var choice = await queuedPrompt(PROMPT_TIMEOUT_MS, function (finish) {
              if (checkGrant(command)) { finish("__GRANTED__"); return }
              return Promise.resolve()
                .then(function () {
                  return ctx.ui.select("Permission Gate: " + command + " may be dangerous.", [
                    "Allow once",
                    "Allow for session",
                    "Always allow",
                    "Deny"
                  ])
                })
                .then(function (c) { finish(c) }, function () { finish(null) })
            })
            if (choice === "__GRANTED__") return
            if (!choice) return { block: true, reason: "Permission gate blocked: command matches dangerous pattern (approval prompt unavailable or timed out — re-run to retry)" }
            if (choice === "Deny") return { block: true, reason: "Permission gate: user denied command" }
            if (choice === "Allow once") return
            var scope = choice === "Always allow" ? "always" : "session"
            saveGrant(command, scope)
          ''
        else
          ''
            return { block: true, reason: "Permission gate blocked: command matches dangerous pattern" }
          ''
      }
            }
          }

          var firstWord = command.trim().split(/\s+/)[0] ?? ""
          if (BLOCKED_COMMANDS.includes(firstWord)) {
      ${
        if modeAsk then
          ''
            var cmdGrant = checkGrant(firstWord)
            if (cmdGrant) return
            if (!ctx.hasUI) return { block: true, reason: "Permission gate blocked: " + firstWord + " is not allowed" }
            if (!ctx.ui || typeof ctx.ui.select !== "function") return { block: true, reason: "Permission gate blocked: " + firstWord + " is not allowed" }
            var cmdChoice = await queuedPrompt(PROMPT_TIMEOUT_MS, function (finish) {
              if (checkGrant(firstWord)) { finish("__GRANTED__"); return }
              return Promise.resolve()
                .then(function () {
                  return ctx.ui.select("Permission Gate: " + firstWord + " is not allowed. Command: " + command, [
                    "Allow once",
                    "Allow for session",
                    "Always allow",
                    "Deny"
                  ])
                })
                .then(function (c) { finish(c) }, function () { finish(null) })
            })
            if (cmdChoice === "__GRANTED__") return
            if (!cmdChoice) return { block: true, reason: "Permission gate blocked: " + firstWord + " is not allowed (approval prompt unavailable or timed out — re-run to retry)" }
            if (cmdChoice === "Deny") return { block: true, reason: "Permission gate: user denied command" }
            if (cmdChoice === "Allow once") return
            var cmdScope = cmdChoice === "Always allow" ? "always" : "session"
            saveGrant(firstWord, cmdScope)
          ''
        else
          ''
            return { block: true, reason: "Permission gate blocked: " + firstWord + " is not allowed" }
          ''
      }
          }
        })
      }
    '';

  mkProtectedPathsHook =
    {
      globs ? defaultProtectedPathGlobs,
      extraGlobs ? [ ],
      protectReads ? true,
      allowPaths ? defaultPathAccessAllowPaths,
      denyPaths ? defaultPathAccessDenyPaths,
      pathAccessMode ? "ask",
      mode ? "ask",
      ...
    }:
    let
      allGlobs = globs ++ extraGlobs;
      readToolGuard =
        if protectReads then
          ''
            if (call.toolName !== "write" && call.toolName !== "edit" && call.toolName !== "filesystem_write_file" && call.toolName !== "read" && call.toolName !== "find" && call.toolName !== "search" && call.toolName !== "grep" && call.toolName !== "filesystem_read_file" && call.toolName !== "filesystem_list_directory") return
          ''
        else
          ''
            if (call.toolName !== "write" && call.toolName !== "edit" && call.toolName !== "filesystem_write_file") return
          '';
      modeAsk = mode == "ask";
      reasonPrefix = if protectReads then "Protected path: accessing " else "Protected path: writing to ";
      pathAccessBlock = pathAccessMode == "block";
      pathAccessAsk = pathAccessMode == "ask";
    in
    ''
      ${lib.optionalString (modeAsk || pathAccessAsk) (mkGrantsHelper {
        grantNamespace = "protectedPaths";
      })}

      var path = require("path")

      const PROTECTED_GLOBS = ${builtins.toJSON allGlobs}
      const ALLOW_PATHS: string[] = ${builtins.toJSON allowPaths}
      const DENY_PATHS: string[] = ${builtins.toJSON denyPaths}

      function escapeRegExp(s: string): string {
        return s.replace(/[|\\{}()[\]^$+?.]/g, "\\$&")
      }

      function matchesWildcard(fp: string, glob: string): boolean {
        var parts = glob.split("*").map(escapeRegExp)
        return new RegExp("^" + parts.join("[^/]*") + "$").test(fp)
      }

      function normalizeToolPath(fp: string): string {
        var expanded = fp
        if (expanded === "~") expanded = process.env.HOME || expanded
        if (expanded.startsWith("~/")) expanded = (process.env.HOME || "") + expanded.slice(1)

        var cwd = path.resolve(process.cwd())
        var resolved = expanded.startsWith("/") ? path.resolve(expanded) : path.resolve(cwd, expanded)
        if (resolved === cwd) return "."
        if (resolved.startsWith(cwd + "/")) return resolved.slice(cwd.length + 1)
        return resolved
      }

      function getToolPath(call): string {
        if (call.toolName === "search" || call.toolName === "grep") {
          return String(call.input?.path ?? call.input?.directory ?? "")
        }
        return String(call.input?.filePath ?? call.input?.path ?? call.input?.directory ?? "")
      }

      function matchesProtected(fp: string): boolean {
        for (const glob of PROTECTED_GLOBS) {
          if (glob.endsWith("/**")) {
            const prefix = glob.slice(0, -3)
            if (fp === prefix || fp.startsWith(prefix + "/")) return true
            if (fp.endsWith("/" + prefix) || fp.includes("/" + prefix + "/")) return true
          } else if (glob.includes("*")) {
            if (matchesWildcard(fp, glob)) return true
            var base = path.basename(fp)
            if (base !== fp && matchesWildcard(base, glob)) return true
          } else {
            if (fp === glob) return true
            if (path.basename(fp) === glob) return true
          }
        }
        return false
      }

      function isInsideWorkspace(absFp: string): boolean {
        if (!absFp) return true
        var cwd = path.resolve(process.cwd())
        return absFp === cwd || absFp.startsWith(cwd + "/")
      }

      function isPathAllowed(absFp: string): boolean {
        for (var i = 0; i < ALLOW_PATHS.length; i++) {
          var ap = ALLOW_PATHS[i]
          if (ap.startsWith("~")) ap = (process.env.HOME || "") + ap.slice(1)
          ap = path.resolve(process.cwd(), ap)
          if (absFp === ap || absFp.startsWith(ap + "/")) return true
        }
        return false
      }

      function isPathDenied(absFp: string): boolean {
        for (var i = 0; i < DENY_PATHS.length; i++) {
          var d = DENY_PATHS[i]
          if (d.startsWith("~")) d = (process.env.HOME || "") + d.slice(1)
          d = path.resolve(d)
          if (absFp === d || absFp.startsWith(d + "/")) return true
        }
        return false
      }

      export default (pi) => {
        pi.on("tool_call", ${
          if (modeAsk || pathAccessAsk) then "async function" else "function"
        } (call, ctx) {
          ${readToolGuard}

          const rawFp = getToolPath(call)
          if (!rawFp) return

          const fp = normalizeToolPath(rawFp)

          // 1. Protected globs — ask or block
          if (matchesProtected(fp)) {
      ${
        if modeAsk then
          ''
            var grant = checkGrant(fp)
            if (grant) return
            if (!ctx.hasUI) return { block: true, reason: "${reasonPrefix}" + fp + " is blocked" }
            if (!ctx.ui || typeof ctx.ui.select !== "function") return { block: true, reason: "${reasonPrefix}" + fp + " is blocked" }
            var choice = await queuedPrompt(PROMPT_TIMEOUT_MS, function (finish) {
              // Re-check grants after the queue — a prior prompt may have granted
              if (checkGrant(fp)) { finish("__GRANTED__"); return }
              return Promise.resolve()
                .then(function () {
                  return ctx.ui.select("Protected Path: " + "${reasonPrefix}" + fp + " is blocked. Allow access?", [
                    "Allow once",
                    "Allow for session",
                    "Always allow",
                    "Deny"
                  ])
                })
                .then(function (c) { finish(c) }, function () { finish(null) })
            })
            if (choice === "__GRANTED__") return
            if (!choice) return { block: true, reason: "${reasonPrefix}" + fp + " is blocked (approval prompt unavailable or timed out — re-run to retry)" }
            if (choice === "Deny") return { block: true, reason: "Protected path: user denied " + fp }
            if (choice === "Allow once") return
            var scope = choice === "Always allow" ? "always" : "session"
            saveGrant(fp, scope)
            return
          ''
        else
          ''
            return { block: true, reason: "${reasonPrefix}" + fp + " is blocked" }
          ''
      }
          }

      ${lib.optionalString (pathAccessMode != "allow") ''
        // 2. Deny list — always blocks
        var absFp = rawFp
        if (absFp.startsWith("~")) absFp = (process.env.HOME || "") + absFp.slice(1)
        if (absFp.startsWith("/")) {
          absFp = path.resolve(absFp)
          if (isPathDenied(absFp)) {
            return { block: true, reason: "Path access denied: " + absFp + " is in the deny list" }
          }
          if (isPathAllowed(absFp)) return
          if (isInsideWorkspace(absFp)) return
          // Outside workspace
          ${
            if pathAccessBlock then
              ''return { block: true, reason: "Path access blocked: " + absFp + " is outside workspace" }''
            else
              ''
                var pgrant = checkGrant(absFp)
                if (pgrant) return
                if (!ctx.hasUI) return { block: true, reason: "Path access blocked: " + absFp + " is outside workspace" }
                if (!ctx.ui || typeof ctx.ui.select !== "function") return { block: true, reason: "Path access blocked: " + absFp + " is outside workspace" }
                var pchoice = await queuedPrompt(PROMPT_TIMEOUT_MS, function (finish) {
                  if (checkGrant(absFp)) { finish("__GRANTED__"); return }
                  return Promise.resolve()
                    .then(function () {
                      return ctx.ui.select("Path Access: " + absFp + " is outside the workspace. Allow access?", [
                        "Allow once",
                        "Allow for session",
                        "Always allow",
                        "Deny"
                      ])
                    })
                    .then(function (c) { finish(c) }, function () { finish(null) })
                })
                if (pchoice === "__GRANTED__") return
                if (!pchoice) return { block: true, reason: "Path access blocked: " + absFp + " is outside workspace (approval prompt unavailable or timed out — re-run to retry)" }
                if (pchoice === "Deny") return { block: true, reason: "Path access denied: " + absFp }
                if (pchoice === "Allow once") return
                var pscope = pchoice === "Always allow" ? "always" : "session"
                saveGrant(absFp, pscope)
              ''
          }
        }
      ''}
        })
      }
    '';

  mkGrantsHelper =
    { grantNamespace }:
    let
      grantsFile = "agent/extensions/grants.json";
    in
    ''
      var sessionGrants: Record<string, string> = {}
      var alwaysGrants: Record<string, string> = {}

      function loadGrants(): void {
        try {
          var fs = require("fs")
          var path = require("path")
          var configDir = process.env.PI_CONFIG_DIR || ".omp"
          var grantsPath = path.join(configDir, "${grantsFile}")
          if (fs.existsSync(grantsPath)) {
            var data = JSON.parse(fs.readFileSync(grantsPath, "utf8"))
            if (data && typeof data === "object") {
              alwaysGrants = data["${grantNamespace}"] || {}
            }
          }
        } catch (_) {
          // grants file missing or invalid — start empty
        }
      }

      function saveGrant(key: string, scope: string): void {
        if (scope === "always") {
          alwaysGrants[key] = "always"
          try {
            var fs = require("fs")
            var path = require("path")
            var configDir = process.env.PI_CONFIG_DIR || ".omp"
            var grantsPath = path.join(configDir, "${grantsFile}")
            var existing: Record<string, any> = {}
            if (fs.existsSync(grantsPath)) {
              existing = JSON.parse(fs.readFileSync(grantsPath, "utf8"))
            }
            existing["${grantNamespace}"] = alwaysGrants
            fs.mkdirSync(path.dirname(grantsPath), { recursive: true })
            fs.writeFileSync(grantsPath, JSON.stringify(existing, null, 2) + "\n")
          } catch (_) {
            // best effort — don't break the hook if save fails
          }
        } else if (scope === "session") {
          sessionGrants[key] = "session"
        }
      }

      function checkGrant(key: string): string | null {
        if (sessionGrants[key]) return sessionGrants[key]
        if (alwaysGrants[key]) return alwaysGrants[key]
        return null
      }

      loadGrants()

      var _promptQueue: Promise<any> = Promise.resolve()
      var PROMPT_TIMEOUT_MS = 25000

      // queuedPrompt runs task once it reaches the front of the queue, so only
      // one ctx.ui.select shows at a time. It resolves with whatever task passes
      // to finish, or null when no answer arrives before deadlineMs (kept well
      // under the runtime 30s tool_call handler cap) — so the handler never times
      // out and a failed or unanswered prompt never leaves the queue rejected.
      function queuedPrompt(deadlineMs, task): Promise<any> {
        return new Promise((resolve) => {
          var settled = false
          var timer
          function finish(v) {
            if (settled) return
            settled = true
            clearTimeout(timer)
            resolve(v)
          }
          timer = setTimeout(function () { finish(null) }, deadlineMs)
          var link = _promptQueue.then(function () {
            if (settled) return
            return task(finish)
          })
          _promptQueue = link.then(function () {}, function () {})
        })
      }
    '';

  defaultPathAccessAllowPaths = [
    "/nix/store"
  ];

  defaultPathAccessDenyPaths = [
    "~/.ssh"
    "~/.gnupg"
  ];

in
{
  inherit
    defaultPermissionGateBlockedCommands
    defaultPermissionGateBlockedPatterns
    defaultProtectedPathGlobs
    defaultPathAccessAllowPaths
    defaultPathAccessDenyPaths
    mkGrantsHelper
    mkPermissionGateHook
    mkProtectedPathsHook
    mkOmpConfig
    mkOmpWrapper
    ;
}
